import { Home } from "./Home";
import { Recomendation } from "./Recomendation";
import { Tour } from "./Tour";
import { Review } from "./Review";
import { Partner } from "./Partner";
import { Subscribe } from "./Subscribe";
import { Footer } from "./Footer";
export { Home };
export { Recomendation };
export { Tour };
export { Review };
export { Partner };
export { Subscribe };
export { Footer };
